{application,yaml_elixir,
             [{applications,[kernel,stdlib,elixir,yamerl]},
              {description,"Yaml parser for Elixir based on native Erlang implementation.\n"},
              {modules,['Elixir.YamlElixir',
                        'Elixir.YamlElixir.FileNotFoundError',
                        'Elixir.YamlElixir.Mapper',
                        'Elixir.YamlElixir.Node.KeywordList',
                        'Elixir.YamlElixir.ParsingError',
                        'Elixir.YamlElixir.Records',
                        'Elixir.YamlElixir.Sigil']},
              {registered,[]},
              {vsn,"2.5.0"}]}.
